[package]
name = "neural_network_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convolutions-rs = "0.3.4"
csv = "1.2.1"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
rand_isaac = "0.3.0"
